/**
 * Самодостаточный словарь чат-подбора (4 языка), портированный из прототипа
 * /Users/mike/Desktop/fun/index.html (объекты I18N[*] — чат-подмножество — и
 * CHAT_I18N[*]).
 *
 * ЗАЧЕМ ОТДЕЛЬНЫЙ СЛОВАРЬ ВНУТРИ ФИЧИ:
 * Все строки чата живут в общем i18n-namespace `common` (его наполняет
 * i18n-агент). Но чтобы фича была самодостаточной и работала независимо от того,
 * успел ли тот агент портировать ВСЕ ключи на ВСЕ языки (на момент написания
 * есть только ru/common.json, а CHAT_I18N-ключей greeting/here/contWa/… там ещё
 * нет), мы регистрируем эти строки в ОТДЕЛЬНОМ namespace `chat` через
 * i18n.addResourceBundle (см. useChatI18n). Чтение идёт с фоллбэком
 * [common, chat]: если перевод уже есть в common — берём его; иначе берём из
 * нашего бандла. Так чат всегда полностью переведён и реактивен к смене языка.
 *
 * Ключи 1-в-1 совпадают с прототипом и с common-namespace, поэтому при появлении
 * перевода в common ничего менять не нужно.
 */
import type { AppLocale } from '@shared/i18n';

/** Плоский словарь «ключ → строка» одного языка. */
export type ChatDict = Record<string, string>;

/**
 * Чат-строки по языкам. Включает:
 *  - подписи опций o_* и op_* (через CHAT_INTENTS.goalKey и intents/options);
 *  - заголовки шагов s1_h..s6_h (используются intents.ts);
 *  - ввод/хендофф: ask_ph, rot_phrases, handoff_or_continue, hand_*, tg_*;
 *  - CHAT_I18N: title / status / greeting / to_manager / assist_off /
 *    reply_time / clear_history / contWa / contTg / contVb.
 *
 * Вестигиальные ключи опросника/контакт-формы/AI-подписей удалены (Pink Ranger):
 * ai_*, f_*, val_*, s*_hint, consent_text, lead_msg, starter_*, here и др.
 */
export const CHAT_DICT: Record<AppLocale, ChatDict> = {
  en: {
    o_student: "Student insurance",
    o_travel: "Travel / international",
    o_reembolso: "With reimbursement",
    o_life: "Life insurance",
    o_decesos: "Funeral cover",
    o_pet: "Pet insurance",
    q_pet: "Tell me, what pet do you have?",
    op_dog: "Dog",
    op_cat: "Cat",
    op_pet_other: "Another pet",
    ask_title: "Have a question? Ask the assistant",
    ask_ph: "Ask about insurance…",
    rot_phrases: 'Visa insurance|Residency insurance|Pet insurance|Dental cover|Travel insurance',
    ask_send: "Ask",
    handoff_or_continue: '…or keep asking your questions here.',
    s1_h: 'Which language is comfortable for you?',
    s2_h: 'What insurance do you need?',
    o_med: 'Health for visa / residency',
    o_dental: 'Dental',
    o_family: 'Family health',
    o_biz: 'For self-employed / business',
    o_other: 'Pet, life or other',
    s3_h: 'Who are we insuring?',
    o_one: 'One person',
    o_pair: 'A couple',
    o_familyk: 'Family with children',
    s4_h: 'Where in Tenerife are you?',
    o_othercity: 'Another area',
    s5_h: 'How urgent is it?',
    o_urgent: 'Urgent — I need it for a visa now',
    o_soon: 'Within the next 1–3 months',
    o_browsing: 'Just exploring for now',
    s6_h: 'Where should the manager message you?',
    load_h: 'Finding a manager for you…',
    done_h: 'The manager has received your request',
    done_p:
      "A personal manager already sees your request and context. Message them now to speed things up — or just wait, they'll contact you.",
    hand_name_ph: 'How should we address you?',
    hand_name_req: 'Please enter your name',
    hand_name_pre: 'My name is',
    hand_need_quote: "I'd like a quote for insurance",
    tg_copy_instr: 'Copy the message and send it to the manager in Telegram:',
    tg_copy: 'Copy message',
    tg_copied: 'Copied ✓',
    tg_open: 'Open manager chat',
    // CHAT_I18N
    clear_history: 'Clear chat',
    title: 'Online insurance finder',
    status: '● online',
    greeting:
      "Hi! 👋 Ask me anything about insurance on Tenerife — I'll help you figure it out and find what fits.",
    to_manager: 'Connect me with a manager',
    assist_off: "Let me connect you with a manager — they'll answer your questions and help you choose.",
    reply_time: 'A manager usually replies within an hour during working hours.',
    contWa: 'Continue in WhatsApp',
    contTg: 'Continue in Telegram',
    contVb: 'Continue in Viber',
  },
  es: {
    o_student: "Seguro para estudiantes",
    o_travel: "Viajes / internacional",
    o_reembolso: "Con reembolso",
    o_life: "Seguro de vida",
    o_decesos: "Seguro de decesos",
    o_pet: "Seguro para mascotas",
    q_pet: "¿Qué mascota tienes?",
    op_dog: "Perro",
    op_cat: "Gato",
    op_pet_other: "Otra mascota",
    ask_title: "¿Tienes una pregunta? Pregunta al asistente",
    ask_ph: "Pregunta sobre seguros…",
    rot_phrases: 'Seguro para visado|Seguro para residencia|Seguro para mascotas|Seguro dental|Seguro de viaje',
    ask_send: "Preguntar",
    handoff_or_continue: '…o sigue preguntando aquí.',
    s1_h: '¿En qué idioma te resulta cómodo hablar?',
    s2_h: '¿Qué seguro necesitas?',
    o_med: 'Salud para visado / residencia',
    o_dental: 'Dental',
    o_family: 'Salud familiar',
    o_biz: 'Para autónomo / empresa',
    o_other: 'Mascota, vida u otro',
    s3_h: '¿A quién aseguramos?',
    o_one: 'Una persona',
    o_pair: 'Una pareja',
    o_familyk: 'Familia con hijos',
    s4_h: '¿En qué zona de Tenerife estás?',
    o_othercity: 'Otra zona',
    s5_h: '¿Qué tan urgente es?',
    o_urgent: 'Urgente — lo necesito para un visado ya',
    o_soon: 'En los próximos 1–3 meses',
    o_browsing: 'Solo estoy informándome',
    s6_h: '¿Dónde quieres que te escriba el gestor?',
    load_h: 'Buscando un gestor para ti…',
    done_h: 'El gestor ha recibido tu solicitud',
    done_p:
      'Un gestor personal ya ve tu solicitud y tu contexto. Escríbele ahora para agilizar — o simplemente espera, te contactará.',
    hand_name_ph: '¿Cómo te llamamos?',
    hand_name_req: 'Por favor, indica tu nombre',
    hand_name_pre: 'Me llamo',
    hand_need_quote: 'Quiero calcular el precio del seguro',
    tg_copy_instr: 'Copia el mensaje y envíalo al gestor en Telegram:',
    tg_copy: 'Copiar mensaje',
    tg_copied: 'Copiado ✓',
    tg_open: 'Abrir chat del gestor',
    clear_history: 'Borrar chat',
    title: 'Buscador de seguros online',
    status: '● en línea',
    greeting:
      '¡Hola! 👋 Pregúntame lo que quieras sobre seguros en Tenerife — te ayudo a entenderlo y a encontrar lo que encaja.',
    to_manager: 'Hablar con un gestor',
    assist_off: 'Te paso con un gestor — responderá tus preguntas y te ayudará a elegir.',
    reply_time: 'El gestor suele responder en menos de una hora en horario laboral.',
    contWa: 'Continuar en WhatsApp',
    contTg: 'Continuar en Telegram',
    contVb: 'Continuar en Viber',
  },
  uk: {
    o_student: "Студентська страховка",
    o_travel: "Подорожі / міжнародна",
    o_reembolso: "З відшкодуванням",
    o_life: "Страхування життя",
    o_decesos: "Похоронна страховка",
    o_pet: "Для тварин",
    q_pet: "Скажіть, яка у вас тварина?",
    op_dog: "Собака",
    op_cat: "Кіт",
    op_pet_other: "Інша тварина",
    ask_title: "Є питання? Запитайте асистента",
    ask_ph: "Запитайте про страхування…",
    rot_phrases: 'Страхування для візи|Страхування для ВНЖ|Страхування тварин|Стоматологія|Страхування подорожей',
    ask_send: "Запитати",
    handoff_or_continue: '…або продовжуйте ставити запитання тут.',
    s1_h: 'Якою мовою вам зручно спілкуватися?',
    s2_h: 'Яка страховка вам потрібна?',
    o_med: 'Медична для візи / ВНЖ',
    o_dental: 'Стоматологія',
    o_family: 'Сімейна медична',
    o_biz: 'Для ФОП / бізнесу',
    o_other: 'Улюбленець, життя або інше',
    s3_h: 'Кого страхуємо?',
    o_one: 'Одна людина',
    o_pair: 'Пара',
    o_familyk: 'Родина з дітьми',
    s4_h: 'У якому районі Тенеріфе ви перебуваєте?',
    o_othercity: 'Інший район',
    s5_h: 'Наскільки терміново?',
    o_urgent: 'Терміново — потрібна для візи зараз',
    o_soon: 'Найближчі 1–3 місяці',
    o_browsing: 'Поки просто дізнаюся умови',
    s6_h: 'Куди менеджеру написати вам?',
    load_h: 'Підбираємо для вас менеджера…',
    done_h: 'Менеджер отримав вашу заявку',
    done_p:
      'Особистий менеджер уже бачить ваш запит і контекст. Напишіть йому зараз, щоб прискорити, — або просто зачекайте, він зв’яжеться з вами.',
    hand_name_ph: 'Як до вас звертатися?',
    hand_name_req: "Будь ласка, вкажіть ім'я",
    hand_name_pre: 'Мене звати',
    hand_need_quote: 'Хочу розрахувати вартість страхування',
    tg_copy_instr: 'Скопіюйте повідомлення та надішліть його менеджеру в Telegram:',
    tg_copy: 'Скопіювати повідомлення',
    tg_copied: 'Скопійовано ✓',
    tg_open: 'Відкрити чат менеджера',
    clear_history: 'Очистити історію',
    title: 'Онлайн-підбір страховки',
    status: '● онлайн',
    greeting:
      'Вітаю! 👋 Запитайте будь-що про страхування на Тенерифе — допоможу розібратися та підібрати відповідний варіант.',
    to_manager: "Зв'язатися з менеджером",
    assist_off: 'Передаю вас менеджеру — він відповість на запитання та допоможе обрати.',
    reply_time: 'Зазвичай менеджер відповідає протягом години в робочий час.',
    contWa: 'Продовжити у WhatsApp',
    contTg: 'Продовжити у Telegram',
    contVb: 'Продовжити у Viber',
  },
  ru: {
    o_student: "Студенческая страховка",
    o_travel: "Путешествия / международная",
    o_reembolso: "С возмещением расходов",
    o_life: "Страхование жизни",
    o_decesos: "Похоронная страховка",
    o_pet: "Для питомцев",
    q_pet: "Скажите, какой у вас питомец?",
    op_dog: "Собака",
    op_cat: "Кошка",
    op_pet_other: "Другой питомец",
    ask_title: "Остались вопросы? Спросите ассистента",
    ask_ph: "Спросите о страховке…",
    rot_phrases: 'Страховка для визы|Страховка для ВНЖ|Страховка для животных|Стоматология|Страховка для путешествий',
    ask_send: "Спросить",
    handoff_or_continue: '…или продолжайте задавать вопросы здесь.',
    s1_h: 'На каком языке вам удобно общаться?',
    s2_h: 'Какая страховка вам нужна?',
    o_med: 'Медицинская для визы / ВНЖ',
    o_dental: 'Стоматология',
    o_family: 'Семейная медицинская',
    o_biz: 'Для ИП / бизнеса',
    o_other: 'Питомец, жизнь или другое',
    s3_h: 'Кого страхуем?',
    o_one: 'Один человек',
    o_pair: 'Пара',
    o_familyk: 'Семья с детьми',
    s4_h: 'В каком районе Тенерифе вы находитесь?',
    o_othercity: 'Другой район',
    s5_h: 'Насколько срочно?',
    o_urgent: 'Срочно — нужна для визы прямо сейчас',
    o_soon: 'В ближайшие 1–3 месяца',
    o_browsing: 'Пока просто узнаю условия',
    s6_h: 'Куда менеджеру написать вам?',
    load_h: 'Подбираем для вас менеджера…',
    done_h: 'Менеджер получил вашу заявку',
    done_p:
      'Личный менеджер уже видит ваш запрос и контекст. Напишите ему сейчас, чтобы ускорить, — или просто дождитесь, он свяжется с вами.',
    hand_name_ph: 'Как к вам обращаться?',
    hand_name_req: 'Пожалуйста, укажите имя',
    hand_name_pre: 'Меня зовут',
    hand_need_quote: 'Мне нужно посчитать стоимость страховки',
    tg_copy_instr: 'Скопируйте сообщение и отправьте его менеджеру в Telegram:',
    tg_copy: 'Скопировать сообщение',
    tg_copied: 'Скопировано ✓',
    tg_open: 'Открыть чат менеджера',
    clear_history: 'Очистить историю',
    title: 'Онлайн-подбор страховки',
    status: '● онлайн',
    greeting:
      'Здравствуйте! 👋 Спросите что угодно о страховке на Тенерифе — помогу разобраться и подобрать подходящий вариант.',
    to_manager: 'Связаться с менеджером',
    assist_off: 'Передаю вас менеджеру — он ответит на вопросы и поможет с выбором.',
    reply_time: 'Обычно менеджер отвечает в течение часа в рабочее время.',
    contWa: 'Продолжить в WhatsApp',
    contTg: 'Продолжить в Telegram',
    contVb: 'Продолжить в Viber',
  },
};

/** Namespace, под которым бандл регистрируется в i18next. */
export const CHAT_NS = 'chat';
