/**
 * Самодостаточный словарь чат-подбора (4 языка), портированный из прототипа
 * /Users/mike/Desktop/fun/index.html (объекты I18N[*] — чат-подмножество — и
 * CHAT_I18N[*]).
 *
 * ЗАЧЕМ ОТДЕЛЬНЫЙ СЛОВАРЬ ВНУТРИ ФИЧИ:
 * Все строки чата живут в общем i18n-namespace `common` (его наполняет
 * i18n-агент). Но чтобы фича была самодостаточной и работала независимо от того,
 * успел ли тот агент портировать ВСЕ ключи на ВСЕ языки (на момент написания
 * есть только ru/common.json, а CHAT_I18N-ключей greeting/here/contWa/… там ещё
 * нет), мы регистрируем эти строки в ОТДЕЛЬНОМ namespace `chat` через
 * i18n.addResourceBundle (см. useChatI18n). Чтение идёт с фоллбэком
 * [common, chat]: если перевод уже есть в common — берём его; иначе берём из
 * нашего бандла. Так чат всегда полностью переведён и реактивен к смене языка.
 *
 * Ключи 1-в-1 совпадают с прототипом и с common-namespace, поэтому при появлении
 * перевода в common ничего менять не нужно.
 */
import type { AppLocale } from '@shared/i18n';

/** Плоский словарь «ключ → строка» одного языка. */
export type ChatDict = Record<string, string>;

/**
 * Чат-строки по языкам. Включает:
 *  - вопросы шагов s1_h..s6_h (+ подсказки s*_hint);
 *  - подписи опций o_* (которые переводятся);
 *  - подписи формы f_* и согласия consent_text;
 *  - экран загрузки/готово load_* / done_*;
 *  - валидационные сообщения val_* и базовое сообщение лида lead_msg;
 *  - CHAT_I18N: title / status / greeting / here / contWa / contTg / contVb.
 *
 * contVb (Viber) добавлен по требованию продукта (предлагаем WhatsApp/Telegram/
 * Viber). В прототипе было только contWa/contTg — формулировка Viber выдержана
 * в том же стиле на каждом языке.
 */
export const CHAT_DICT: Record<AppLocale, ChatDict> = {
  en: {
    ask_or: "or ask your own question",
    ai_label: "How matching works",
    ai_note: "An AI assistant helps you here with general insurance guidance. A manager always confirms the details and the quote.",
    o_student: "Student insurance",
    o_travel: "Travel / international",
    o_reembolso: "With reimbursement",
    o_life: "Life insurance",
    o_decesos: "Funeral cover",
    o_pet: "Pet insurance",
    q_pet: "Tell me, what pet do you have?",
    op_dog: "Dog",
    op_cat: "Cat",
    op_pet_other: "Another pet",
    ask_title: "Have a question? Ask the assistant",
    ask_ph: "Ask about insurance…",
    rot_phrases: 'Visa insurance|Residency insurance|Pet insurance|Dental cover|Travel insurance',
    ask_send: "Ask",
    handoff_or_continue: '…or keep asking your questions here.',
    ask_cta: "Ask your own question",
    starters_label: "Popular questions",
    starter_visa: "Which policy works for a residency visa?",
    starter_price: "How much does health insurance cost?",
    starter_dental: "Is dental care included?",
    ask_thinking: "Assistant is typing…",
    s1_h: 'Which language is comfortable for you?',
    s1_hint: "We'll find a manager who speaks your language.",
    s2_h: 'What insurance do you need?',
    s2_hint: 'Pick the main goal — the manager will clarify the details.',
    o_med: 'Health for visa / residency',
    o_dental: 'Dental',
    o_family: 'Family health',
    o_biz: 'For self-employed / business',
    o_other: 'Pet, life or other',
    s3_h: 'Who are we insuring?',
    s3_hint: 'This affects the coverage.',
    o_one: 'One person',
    o_pair: 'A couple',
    o_familyk: 'Family with children',
    s4_h: 'Where in Tenerife are you?',
    s4_hint: "We'll find the nearest office and manager.",
    o_othercity: 'Another area',
    s5_h: 'How urgent is it?',
    s5_hint: "We'll help set the priority.",
    o_urgent: 'Urgent — I need it for a visa now',
    o_soon: 'Within the next 1–3 months',
    o_browsing: 'Just exploring for now',
    s6_h: 'Where should the manager message you?',
    s6_hint: "Pick a messenger — that's where your match arrives. No calls.",
    f_name_l: 'Your name',
    f_name_ph: 'For example, Anna',
    f_msgr_l: 'Preferred messenger',
    f_contact_l: 'Phone or @username',
    f_contact_ph: '+34 600 000 000 or @username',
    consent_text:
      'I agree to the processing of my data to find insurance and contact me.',
    btn_send: 'Send request',
    q_back: '← Back',
    q_free: 'Free, no obligations',
    load_h: 'Finding a manager for you…',
    load_p: 'Sending your request to a Tenerife office',
    done_h: 'The manager has received your request',
    done_p:
      "A personal manager already sees your request and context. Message them now to speed things up — or just wait, they'll contact you.",
    done_restart: 'Start over',
    val_name: 'Please enter your name',
    val_contact: 'Enter a phone or username',
    val_consent: 'Consent to data processing is required',
    lead_msg: 'Hi! I filled out the insurance finder on the website.',
    hand_name_ph: 'How should we address you?',
    hand_name_req: 'Please enter your name',
    hand_name_pre: 'My name is',
    hand_hello: 'Hello!',
    hand_need_quote: "I'd like a quote for insurance",
    tg_copy_instr: 'Copy the message and send it to the manager in Telegram:',
    tg_copy: 'Copy message',
    tg_copied: 'Copied ✓',
    tg_open: 'Open manager chat',
    // CHAT_I18N
    title: 'Online insurance finder',
    status: '● online',
    greeting:
      "Hi! 👋 Tell me what insurance you're looking for — I'll answer your questions and then connect you with a manager.",
    to_manager: 'Connect me with a manager',
    assist_off: "Let me connect you with a manager — they'll answer your questions and help you choose.",
    reply_time: 'We usually reply within an hour during working hours.',
    here: 'You can keep chatting right here — the manager will reply as soon as they join.',
    contWa: 'Continue in WhatsApp',
    contTg: 'Continue in Telegram',
    contVb: 'Continue in Viber',
  },
  es: {
    ask_or: "o haz tu propia pregunta",
    ai_label: "Cómo funciona",
    ai_note: "Aquí te orienta un asistente de IA con información general sobre seguros. Un gestor confirma siempre los detalles y el presupuesto.",
    o_student: "Seguro para estudiantes",
    o_travel: "Viajes / internacional",
    o_reembolso: "Con reembolso",
    o_life: "Seguro de vida",
    o_decesos: "Seguro de decesos",
    o_pet: "Seguro para mascotas",
    q_pet: "¿Qué mascota tienes?",
    op_dog: "Perro",
    op_cat: "Gato",
    op_pet_other: "Otra mascota",
    ask_title: "¿Tienes una pregunta? Pregunta al asistente",
    ask_ph: "Pregunta sobre seguros…",
    rot_phrases: 'Seguro para visado|Seguro para residencia|Seguro para mascotas|Seguro dental|Seguro de viaje',
    ask_send: "Preguntar",
    handoff_or_continue: '…o sigue preguntando aquí.',
    ask_cta: "Haz tu propia pregunta",
    starters_label: "Preguntas frecuentes",
    starter_visa: "¿Qué seguro sirve para el visado de residencia?",
    starter_price: "¿Cuánto cuesta el seguro de salud?",
    starter_dental: "¿Incluye atención dental?",
    ask_thinking: "El asistente está escribiendo…",
    s1_h: '¿En qué idioma te resulta cómodo hablar?',
    s1_hint: 'Buscaremos un gestor que hable tu idioma.',
    s2_h: '¿Qué seguro necesitas?',
    s2_hint: 'Elige el objetivo principal — el gestor aclarará los detalles.',
    o_med: 'Salud para visado / residencia',
    o_dental: 'Dental',
    o_family: 'Salud familiar',
    o_biz: 'Para autónomo / empresa',
    o_other: 'Mascota, vida u otro',
    s3_h: '¿A quién aseguramos?',
    s3_hint: 'Esto afecta a la cobertura.',
    o_one: 'Una persona',
    o_pair: 'Una pareja',
    o_familyk: 'Familia con hijos',
    s4_h: '¿En qué zona de Tenerife estás?',
    s4_hint: 'Buscaremos la oficina y el gestor más cercanos.',
    o_othercity: 'Otra zona',
    s5_h: '¿Qué tan urgente es?',
    s5_hint: 'Te ayudamos a priorizar.',
    o_urgent: 'Urgente — lo necesito para un visado ya',
    o_soon: 'En los próximos 1–3 meses',
    o_browsing: 'Solo estoy informándome',
    s6_h: '¿Dónde quieres que te escriba el gestor?',
    s6_hint: 'Elige una mensajería — ahí llegará tu propuesta. Sin llamadas.',
    f_name_l: 'Tu nombre',
    f_name_ph: 'Por ejemplo, Ana',
    f_msgr_l: 'Mensajería preferida',
    f_contact_l: 'Teléfono o @usuario',
    f_contact_ph: '+34 600 000 000 o @usuario',
    consent_text:
      'Acepto el tratamiento de mis datos para buscar un seguro y contactarme.',
    btn_send: 'Enviar solicitud',
    q_back: '← Atrás',
    q_free: 'Gratis y sin compromiso',
    load_h: 'Buscando un gestor para ti…',
    load_p: 'Enviando tu solicitud a una oficina en Tenerife',
    done_h: 'El gestor ha recibido tu solicitud',
    done_p:
      'Un gestor personal ya ve tu solicitud y tu contexto. Escríbele ahora para agilizar — o simplemente espera, te contactará.',
    done_restart: 'Empezar de nuevo',
    val_name: 'Por favor, indica tu nombre',
    val_contact: 'Indica un teléfono o usuario',
    val_consent: 'Se requiere el consentimiento de datos',
    lead_msg: '¡Hola! He completado el buscador de seguros en la web.',
    hand_name_ph: '¿Cómo te llamamos?',
    hand_name_req: 'Por favor, indica tu nombre',
    hand_name_pre: 'Me llamo',
    hand_hello: '¡Hola!',
    hand_need_quote: 'Quiero calcular el precio del seguro',
    tg_copy_instr: 'Copia el mensaje y envíalo al gestor en Telegram:',
    tg_copy: 'Copiar mensaje',
    tg_copied: 'Copiado ✓',
    tg_open: 'Abrir chat del gestor',
    title: 'Buscador de seguros online',
    status: '● en línea',
    greeting:
      '¡Hola! 👋 Cuéntame qué seguro buscas — respondo tus preguntas y luego te paso con un gestor.',
    to_manager: 'Hablar con un gestor',
    assist_off: 'Te paso con un gestor — responderá tus preguntas y te ayudará a elegir.',
    reply_time: 'Solemos responder en menos de una hora en horario laboral.',
    here: 'Puedes seguir chateando aquí mismo — el gestor responderá en cuanto se conecte.',
    contWa: 'Continuar en WhatsApp',
    contTg: 'Continuar en Telegram',
    contVb: 'Continuar en Viber',
  },
  uk: {
    ask_or: "або запитайте своє",
    ai_label: "Як працює підбір",
    ai_note: "Тут вам допомагає ШІ-асистент із загальною інформацією про страхування. Менеджер завжди підтверджує деталі та розрахунок.",
    o_student: "Студентська страховка",
    o_travel: "Подорожі / міжнародна",
    o_reembolso: "З відшкодуванням",
    o_life: "Страхування життя",
    o_decesos: "Похоронна страховка",
    o_pet: "Для тварин",
    q_pet: "Скажіть, яка у вас тварина?",
    op_dog: "Собака",
    op_cat: "Кіт",
    op_pet_other: "Інша тварина",
    ask_title: "Є питання? Запитайте асистента",
    ask_ph: "Запитайте про страхування…",
    rot_phrases: 'Страхування для візи|Страхування для ВНЖ|Страхування тварин|Стоматологія|Страхування подорожей',
    ask_send: "Запитати",
    handoff_or_continue: '…або продовжуйте ставити запитання тут.',
    ask_cta: "Поставити своє запитання",
    starters_label: "Популярні питання",
    starter_visa: "Який поліс підходить для візи на ВНЖ?",
    starter_price: "Скільки коштує медичне страхування?",
    starter_dental: "Чи входить стоматологія?",
    ask_thinking: "Асистент друкує…",
    s1_h: 'Якою мовою вам зручно спілкуватися?',
    s1_hint: 'Підберемо менеджера, який говорить вашою мовою.',
    s2_h: 'Яка страховка вам потрібна?',
    s2_hint: 'Оберіть головну мету — деталі уточнить менеджер.',
    o_med: 'Медична для візи / ВНЖ',
    o_dental: 'Стоматологія',
    o_family: 'Сімейна медична',
    o_biz: 'Для ФОП / бізнесу',
    o_other: 'Улюбленець, життя або інше',
    s3_h: 'Кого страхуємо?',
    s3_hint: 'Це впливає на підбір покриття.',
    o_one: 'Одна людина',
    o_pair: 'Пара',
    o_familyk: 'Родина з дітьми',
    s4_h: 'У якому районі Тенеріфе ви перебуваєте?',
    s4_hint: 'Підберемо найближчий офіс і менеджера.',
    o_othercity: 'Інший район',
    s5_h: 'Наскільки терміново?',
    s5_hint: 'Допоможемо розставити пріоритет.',
    o_urgent: 'Терміново — потрібна для візи зараз',
    o_soon: 'Найближчі 1–3 місяці',
    o_browsing: 'Поки просто дізнаюся умови',
    s6_h: 'Куди менеджеру написати вам?',
    s6_hint: 'Оберіть месенджер — туди прийде підбір. Без дзвінків.',
    f_name_l: "Ваше ім'я",
    f_name_ph: 'Наприклад, Анна',
    f_msgr_l: 'Зручний месенджер',
    f_contact_l: 'Телефон або @username',
    f_contact_ph: '+34 600 000 000 або @username',
    consent_text:
      'Я погоджуюсь на обробку моїх даних для підбору страховки і зв’язку зі мною.',
    btn_send: 'Надіслати заявку',
    q_back: '← Назад',
    q_free: 'Безкоштовно і ні до чого не зобов’язує',
    load_h: 'Підбираємо для вас менеджера…',
    load_p: 'Передаємо вашу заявку в офіс на Тенеріфе',
    done_h: 'Менеджер отримав вашу заявку',
    done_p:
      'Особистий менеджер уже бачить ваш запит і контекст. Напишіть йому зараз, щоб прискорити, — або просто зачекайте, він зв’яжеться з вами.',
    done_restart: 'Пройти підбір заново',
    val_name: "Будь ласка, вкажіть ім'я",
    val_contact: 'Вкажіть телефон або username',
    val_consent: 'Потрібна згода на обробку даних',
    lead_msg: 'Вітаю! Заповнив підбір страховки на сайті.',
    hand_name_ph: 'Як до вас звертатися?',
    hand_name_req: "Будь ласка, вкажіть ім'я",
    hand_name_pre: 'Мене звати',
    hand_hello: 'Вітаю!',
    hand_need_quote: 'Хочу розрахувати вартість страхування',
    tg_copy_instr: 'Скопіюйте повідомлення та надішліть його менеджеру в Telegram:',
    tg_copy: 'Скопіювати повідомлення',
    tg_copied: 'Скопійовано ✓',
    tg_open: 'Відкрити чат менеджера',
    title: 'Онлайн-підбір страховки',
    status: '● онлайн',
    greeting:
      'Вітаю! 👋 Розкажіть, яке страхування вам потрібне — відповім на запитання та передам менеджеру.',
    to_manager: "Зв'язатися з менеджером",
    assist_off: 'Передаю вас менеджеру — він відповість на запитання та допоможе обрати.',
    reply_time: 'Зазвичай відповідаємо протягом години в робочий час.',
    here: 'Можете продовжити листування просто тут — менеджер відповість, щойно підключиться.',
    contWa: 'Продовжити у WhatsApp',
    contTg: 'Продовжити у Telegram',
    contVb: 'Продовжити у Viber',
  },
  ru: {
    ask_or: "или спросите своё",
    ai_label: "Как работает подбор",
    ai_note: "Здесь вам помогает ИИ-ассистент с общей информацией о страховках. Менеджер всегда подтверждает детали и расчёт.",
    o_student: "Студенческая страховка",
    o_travel: "Путешествия / международная",
    o_reembolso: "С возмещением расходов",
    o_life: "Страхование жизни",
    o_decesos: "Похоронная страховка",
    o_pet: "Для питомцев",
    q_pet: "Скажите, какой у вас питомец?",
    op_dog: "Собака",
    op_cat: "Кошка",
    op_pet_other: "Другой питомец",
    ask_title: "Остались вопросы? Спросите ассистента",
    ask_ph: "Спросите о страховке…",
    rot_phrases: 'Страховка для визы|Страховка для ВНЖ|Страховка для животных|Стоматология|Страховка для путешествий',
    ask_send: "Спросить",
    handoff_or_continue: '…или продолжайте задавать вопросы здесь.',
    ask_cta: "Задать свой вопрос",
    starters_label: "Частые вопросы",
    starter_visa: "Какой полис подходит для визы на ВНЖ?",
    starter_price: "Сколько стоит медицинская страховка?",
    starter_dental: "Входит ли стоматология?",
    ask_thinking: "Ассистент печатает…",
    s1_h: 'На каком языке вам удобно общаться?',
    s1_hint: 'Подберём менеджера, говорящего на вашем языке.',
    s2_h: 'Какая страховка вам нужна?',
    s2_hint: 'Выберите главную цель — детали уточнит менеджер.',
    o_med: 'Медицинская для визы / ВНЖ',
    o_dental: 'Стоматология',
    o_family: 'Семейная медицинская',
    o_biz: 'Для ИП / бизнеса',
    o_other: 'Питомец, жизнь или другое',
    s3_h: 'Кого страхуем?',
    s3_hint: 'Это влияет на подбор покрытия.',
    o_one: 'Один человек',
    o_pair: 'Пара',
    o_familyk: 'Семья с детьми',
    s4_h: 'В каком районе Тенерифе вы находитесь?',
    s4_hint: 'Подберём ближайший офис и менеджера.',
    o_othercity: 'Другой район',
    s5_h: 'Насколько срочно?',
    s5_hint: 'Поможем расставить приоритет.',
    o_urgent: 'Срочно — нужна для визы прямо сейчас',
    o_soon: 'В ближайшие 1–3 месяца',
    o_browsing: 'Пока просто узнаю условия',
    s6_h: 'Куда менеджеру написать вам?',
    s6_hint: 'Выберите мессенджер — туда придёт подбор. Без звонков.',
    f_name_l: 'Ваше имя',
    f_name_ph: 'Например, Анна',
    f_msgr_l: 'Удобный мессенджер',
    f_contact_l: 'Телефон или @username',
    f_contact_ph: '+34 600 000 000 или @username',
    consent_text:
      'Я согласен на обработку моих данных для подбора страховки и связи со мной.',
    btn_send: 'Отправить заявку',
    q_back: '← Назад',
    q_free: 'Бесплатно и ни к чему не обязывает',
    load_h: 'Подбираем для вас менеджера…',
    load_p: 'Передаём вашу заявку в офис на Тенерифе',
    done_h: 'Менеджер получил вашу заявку',
    done_p:
      'Личный менеджер уже видит ваш запрос и контекст. Напишите ему сейчас, чтобы ускорить, — или просто дождитесь, он свяжется с вами.',
    done_restart: 'Пройти подбор заново',
    val_name: 'Пожалуйста, укажите имя',
    val_contact: 'Укажите телефон или username',
    val_consent: 'Нужно согласие на обработку данных',
    lead_msg: 'Здравствуйте! Заполнил подбор страховки на сайте.',
    hand_name_ph: 'Как к вам обращаться?',
    hand_name_req: 'Пожалуйста, укажите имя',
    hand_name_pre: 'Меня зовут',
    hand_hello: 'Здравствуйте!',
    hand_need_quote: 'Мне нужно посчитать стоимость страховки',
    tg_copy_instr: 'Скопируйте сообщение и отправьте его менеджеру в Telegram:',
    tg_copy: 'Скопировать сообщение',
    tg_copied: 'Скопировано ✓',
    tg_open: 'Открыть чат менеджера',
    title: 'Онлайн-подбор страховки',
    status: '● онлайн',
    greeting:
      'Здравствуйте! 👋 Расскажите, какая страховка вам нужна — отвечу на вопросы и передам менеджеру.',
    to_manager: 'Связаться с менеджером',
    assist_off: 'Передаю вас менеджеру — он ответит на вопросы и поможет с выбором.',
    reply_time: 'Обычно отвечаем в течение часа в рабочее время.',
    here: 'Можете продолжить переписку прямо здесь — менеджер ответит, как только подключится.',
    contWa: 'Продолжить в WhatsApp',
    contTg: 'Продолжить в Telegram',
    contVb: 'Продолжить в Viber',
  },
};

/** Namespace, под которым бандл регистрируется в i18next. */
export const CHAT_NS = 'chat';
